load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("@rules_cc//cc:defs.bzl", "cc_library")

AWSLC_VERSION = "1.66.1"
OPENSSL_VERSION_NUMBER = "0x1010107f"

package(default_visibility = ["//visibility:public"])

expand_template(
    name = "base_h",
    out = "base.h",
    substitutions = {
        "@OPENSSL_VERSION_NUMBER@": OPENSSL_VERSION_NUMBER,
        "@SOFTWARE_VERSION@": AWSLC_VERSION,
    },
    template = "base.h.in",
)

expand_template(
    name = "opensslv_h",
    out = "opensslv.h",
    substitutions = {
        "@OPENSSL_VERSION_NUMBER@": OPENSSL_VERSION_NUMBER,
    },
    template = "opensslv.h.in",
)

filegroup(
    name = "public_headers",
    srcs = glob(
        ["**/*.h"],
    ),
)

cc_library(
    name = "headers",
    hdrs = [
        ":public_headers",
        ":base_h",
        ":opensslv_h",
    ],
    includes = [".."],
)
